# -------------------------------------------------------------------
# Fluid 主题覆盖配置
# -------------------------------------------------------------------

# 搜索功能
search:
  enable: true
  # 开启本地静态搜索
  type: local
